env: "dev"
sql:
  dialect: "mysql"
  connection: "root:helloworld@tcp(localhost:6603)/godb?charset=utf8&parseTime=True"
redis:
  connection: "127.0.0.1:6379"
mongodb:
  connection: "mongodb://localhost:27017/"